/* This file is auto-generated by @proto.ui/cli. */
/* Do not edit by hand. */

export { BaseButtonElement } from './wc';
export { BaseDialogRootElement } from './wc';
export { BaseDialogTriggerElement } from './wc';
export { BaseDialogMaskElement } from './wc';
export { BaseDialogContentElement } from './wc';
export { BaseDialogTitleElement } from './wc';
export { BaseDialogDescriptionElement } from './wc';
export { BaseDialogCloseElement } from './wc';
export { BaseSelectRootElement } from './wc';
export { BaseSelectTriggerElement } from './wc';
export { BaseSelectValueElement } from './wc';
export { BaseSelectContentElement } from './wc';
export { BaseSelectItemElement } from './wc';
export { BaseTabsRootElement } from './wc';
export { BaseTabsListElement } from './wc';
export { BaseTabsTriggerElement } from './wc';
export { BaseTabsContentElement } from './wc';
export { BaseToggleElement } from './wc';
