/* This file is auto-generated by @proto.ui/cli. */
/* Do not edit by hand. */

import { AdaptToWebComponent } from '@proto.ui/adapter-web-component';
import { button } from '@proto.ui/prototypes-base/button';
import { dialogClose, dialogContent, dialogDescription, dialogMask, dialogRoot, dialogTitle, dialogTrigger } from '@proto.ui/prototypes-base/dialog';
import { selectContent, selectItem, selectRoot, selectTrigger, selectValue } from '@proto.ui/prototypes-base/select';
import { tabsContent, tabsList, tabsRoot, tabsTrigger } from '@proto.ui/prototypes-base/tabs';
import { toggle } from '@proto.ui/prototypes-base/toggle';

export const BaseButtonElement = AdaptToWebComponent(button, { registerAs: 'proto-ui-base-button' });

export const BaseDialogRootElement = AdaptToWebComponent(dialogRoot, { registerAs: 'proto-ui-base-dialog-root' });
export const BaseDialogTriggerElement = AdaptToWebComponent(dialogTrigger, { registerAs: 'proto-ui-base-dialog-trigger' });
export const BaseDialogMaskElement = AdaptToWebComponent(dialogMask, { registerAs: 'proto-ui-base-dialog-mask' });
export const BaseDialogContentElement = AdaptToWebComponent(dialogContent, { registerAs: 'proto-ui-base-dialog-content' });
export const BaseDialogTitleElement = AdaptToWebComponent(dialogTitle, { registerAs: 'proto-ui-base-dialog-title' });
export const BaseDialogDescriptionElement = AdaptToWebComponent(dialogDescription, { registerAs: 'proto-ui-base-dialog-description' });
export const BaseDialogCloseElement = AdaptToWebComponent(dialogClose, { registerAs: 'proto-ui-base-dialog-close' });

export const BaseSelectRootElement = AdaptToWebComponent(selectRoot, { registerAs: 'proto-ui-base-select-root' });
export const BaseSelectTriggerElement = AdaptToWebComponent(selectTrigger, { registerAs: 'proto-ui-base-select-trigger' });
export const BaseSelectValueElement = AdaptToWebComponent(selectValue, { registerAs: 'proto-ui-base-select-value' });
export const BaseSelectContentElement = AdaptToWebComponent(selectContent, { registerAs: 'proto-ui-base-select-content' });
export const BaseSelectItemElement = AdaptToWebComponent(selectItem, { registerAs: 'proto-ui-base-select-item' });

export const BaseTabsRootElement = AdaptToWebComponent(tabsRoot, { registerAs: 'proto-ui-base-tabs-root' });
export const BaseTabsListElement = AdaptToWebComponent(tabsList, { registerAs: 'proto-ui-base-tabs-list' });
export const BaseTabsTriggerElement = AdaptToWebComponent(tabsTrigger, { registerAs: 'proto-ui-base-tabs-trigger' });
export const BaseTabsContentElement = AdaptToWebComponent(tabsContent, { registerAs: 'proto-ui-base-tabs-content' });

export const BaseToggleElement = AdaptToWebComponent(toggle, { registerAs: 'proto-ui-base-toggle' });
